## **ECE2112: Programming Assessment 2**

 *Submitted by: Jazmine Mikaela L. Rafols | 2ECE-D*  
 *Submitted on: August 28, 2026*

### **A. Reproducible Normalization Problem**
---

In [113]:
import numpy as np

In [114]:
np.random.seed(2112)
X = np.random.randint(10,101,size=(5,5))

In [115]:
print(X)

[[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]


In [116]:
float(X.mean()), float(X.std())

(46.36, 25.864075471588002)

In [117]:
print("Array X has a rounded mean of: ", np.round(X.mean(),0))

Array X has a rounded mean of:  46.0


In [118]:
print("Array X has a rounded standard deviation of: ", np.round(X.std(),1))

Array X has a rounded standard deviation of:  25.9


In [119]:
X_normalized = (X - X.mean()) / X.std()
print(X_normalized)

[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]


In [120]:
print("Array X has a rounded normalized mean of: ", np.round(X_normalized.mean(),0))

Array X has a rounded normalized mean of:  0.0


In [121]:
print("Array X has a rounded normalized standard deviation of: ", np.round(X_normalized.std(),1))

Array X has a rounded normalized standard deviation of:  1.0


In [122]:
np.save("X_normalized.npy", np.ndarray)

### **B. Cubes Divisible by 4 Problem**
---

In [123]:
C = np.arange(1, 101).reshape(10,10) ** 3
print(C)

[[      1       8      27      64     125     216     343     512     729
     1000]
 [   1331    1728    2197    2744    3375    4096    4913    5832    6859
     8000]
 [   9261   10648   12167   13824   15625   17576   19683   21952   24389
    27000]
 [  29791   32768   35937   39304   42875   46656   50653   54872   59319
    64000]
 [  68921   74088   79507   85184   91125   97336  103823  110592  117649
   125000]
 [ 132651  140608  148877  157464  166375  175616  185193  195112  205379
   216000]
 [ 226981  238328  250047  262144  274625  287496  300763  314432  328509
   343000]
 [ 357911  373248  389017  405224  421875  438976  456533  474552  493039
   512000]
 [ 531441  551368  571787  592704  614125  636056  658503  681472  704969
   729000]
 [ 753571  778688  804357  830584  857375  884736  912673  941192  970299
  1000000]]


In [124]:
div_by_4 = C[C % 4 == 0]
print(div_by_4)

[      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]


In [125]:
print("The total number of cubed values that are divisible by 4: ", div_by_4.shape)

The total number of cubed values that are divisible by 4:  (50,)


In [126]:
np.save("div_by_4.npy", np.ndarray)

### **C. Above-Mean Squares Problem**
---

In [127]:
S = np.arange(1, 37).reshape(6,6) ** 2
print(S)

[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]


In [128]:
S_mean = S.mean()
print("Array S has a rounded mean of: ", np.round(S_mean,2))

Array S has a rounded mean of:  450.17


In [129]:
above_mean = S[S > S_mean]
print(above_mean)

[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]


In [130]:
print("The total number of selected elements that are greater than the mean: ", above_mean.shape)

The total number of selected elements that are greater than the mean:  (15,)


In [131]:
np.save("above_mean.npy", np.ndarray)